n = input('Digite algo: ')
t = type(n)
s = n.isspace()
nu = n.isnumeric()
a = n.isalpha()
an = n.isalnum()
ma = n.isupper()
mi = n.islower()
print('O tipo primitivo desse valor é {}'.format(t))
print('Só tem espaços? {}'.format(s))
print('è um numero? {}'.format(nu))
print('É alfabético? {}'.format(a))
print('É alfanumérico? {}'.format(an))
print('Está em maiúsculas? {}'.format(ma))
print('Esta em minusculas? {}'.format(mi))
print('Está capitalizada?', n.istitle())
# pode se fazer tudo na mesma linha, sem precisar transformar e variável